### ISSUE TITLE
[rule] Output files should be put in `titanic/out`, rather than `titanic/`

### ISSUE THREAD

**Issue by ryunosuke-yamashita** [tokyotech-toyota/titanic#1]
Hi, @tokyotech-toyota/general,

Top directory `titanic/` should be ALWAYS clean.
Output files should be put in `titanic/out`.
Can anyone modify `preprocess.py` in order to do this?

**Comment by ksgarnet** [comment]
@ryunosuke-yamashita,
Thank you for your proposal.
I modified preprocess.py to put outputs in /out directory.

**Comment by ryunosuke-yamashita** [comment]
@ksgarnet,
Thanks for your fixing.
I'll close this issue.
